# Generated by Django 4.2.1 on 2023-06-16 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billFromAddress', models.CharField(max_length=100)),
                ('fromCity', models.CharField(max_length=100)),
                ('fromPostCode', models.CharField(max_length=100)),
                ('fromCountry', models.CharField(max_length=100)),
                ('clientName', models.CharField(max_length=100)),
                ('clientEmail', models.EmailField(max_length=100)),
                ('clientStreetAddress', models.CharField(max_length=100)),
                ('toCity', models.CharField(max_length=100)),
                ('toPostCode', models.CharField(max_length=100)),
                ('toCountry', models.CharField(max_length=100)),
                ('invoiceDate', models.DateField(auto_now_add=True)),
                ('paymentTerms', models.CharField(blank=True, max_length=100)),
                ('projectDescription', models.CharField(max_length=200)),
                ('invoiceStatus', models.CharField(blank=True, max_length=100)),
                ('markAsPaid', models.BooleanField(default=False)),
                ('items', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('itemQty', models.IntegerField()),
                ('itemPrice', models.IntegerField()),
                ('totalItem', models.CharField(blank=True, max_length=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.invoice')),
            ],
        ),
    ]
