# Generated by Django 4.2.1 on 2023-06-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetAddress', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postCode', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('clientName', models.CharField(max_length=100)),
                ('clientEmail', models.EmailField(max_length=100)),
                ('clientStreetAddress', models.CharField(max_length=100)),
                ('clientCity', models.CharField(max_length=100)),
                ('clientPostCode', models.CharField(max_length=100)),
                ('clientCountry', models.CharField(max_length=100)),
                ('invoiceDate', models.DateField(auto_now_add=True)),
                ('paymentTerms', models.CharField(max_length=100)),
                ('projectDescription', models.CharField(max_length=200)),
                ('itemName', models.CharField(max_length=100)),
                ('itemQuantity', models.CharField(max_length=100)),
                ('itemPrice', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
            ],
        ),
    ]
